name: Terraform variable and output descriptions checker

author: Stephen Attard

description: Check that all variables and outputs objects have descriptions in your terraform code

inputs:
  path:
    description: 'Path to the terraform code'
    required: true
    default: '.'

outputs:
  exitcode:
    description: "The exitcode of the action"
    value: ${{ steps.run-checker.outputs.exitcode }}

runs:
  using: composite
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::This action is only supported on Linux Runners"
        exit 1
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: run-checker
      id: run-checker
      shell: bash
      run: |
        pip install --quiet --upgrade pip
        pip install --quiet python-hcl2==4.3.2
        set +e
        url="https://raw.githubusercontent.com/stephenattard/terraform-variable-and-output-descriptions-checker/${{ github.sha }}/src/run.py"
        echo "Downloading from $url"
        curl $url --output ${{ runner.temp }}/checker.py
        python ${{ runner.temp }}/checker.py ${{ inputs.path }}
        exitcode="$?"
        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        exit "$exitcode"
branding:
  color: green
  icon: box