name: Testing descriptions checker

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  passing-test:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.test-passing.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: test-passing
        continue-on-error: false
        with:
          path: "test/passing"

  failing-test:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.test-failing.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: test-failing
        continue-on-error: true
        with:
          path: "test/failing"

  report-to-pr:
    runs-on: ubuntu-latest
    needs:
      - passing-test
      - failing-test
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide: true
          message: |
            Test pass exited with code ${{ needs.passing-test.outputs.exitcode }}
            Test fail exited with code ${{ needs.failing-test.outputs.exitcode }}