name: Testing descriptions checker

on:
  pull_request:
    branches:
      - main

jobs:
  test-descriptions-checker-passing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          path: "test/passing"
  test-descriptions-checker-failing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        continue-on-error: true
        with:
          path: "test/failing"
